name: rogue_shooter
description: A simple game benchmarking the collision detection performance.
homepage: https://github.com/flame-engine/flame/tree/main/examples/games/rogue_shooter
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  backbone:
    git:
      url: https://github.com/sturdykeep/backbone.git
      ref: main
  flame: ^1.6.0
  flutter:
    sdk: flutter
  perfmon_logger:
    git:
      url: https://github.com/sturdykeep/backbone_dev_tooling.git
      path: perfmon_logger/
      ref: main
 

dev_dependencies:
  flame_lint: ^0.2.0

flutter:
  assets:
    - assets/images/rogue_shooter/
